name: Deploy Palmotićeva Sanctuary to Google Cloud Run

on:
  push:
    branches:
      - main # Or 'master', or your primary deployment branch

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_ARTIFACT_REGISTRY_LOCATION: ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }} # e.g., europe-west1
  GCP_ARTIFACT_REPO_NAME: ${{ secrets.GCP_ARTIFACT_REPO_NAME }} # e.g., palmoticeva-repo
  CLOUD_RUN_SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE_NAME }} # e.g., palmoticeva-sanctuary
  CLOUD_RUN_REGION: ${{ secrets.CLOUD_RUN_REGION }} # e.g., europe-west1
  # IMAGE_NAME format: location-docker.pkg.dev/project-id/repo-name/service-name:commit-sha
  IMAGE_NAME: ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO_NAME }}/${{ secrets.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker to use gcloud
      run: gcloud auth configure-docker ${{ env.GCP_ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

    - name: Build Docker image
      # Using --file to specify Dockerfile path relative to workspace,
      # and workspace as the build context.
      run: docker build --file ${{ github.workspace }}/Dockerfile -t ${{ env.IMAGE_NAME }} ${{ github.workspace }}

    - name: Push Docker image to Artifact Registry
      run: docker push ${{ env.IMAGE_NAME }}

    - name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ env.CLOUD_RUN_SERVICE_NAME }}
        region: ${{ env.CLOUD_RUN_REGION }}
        image: ${{ env.IMAGE_NAME }}
        env_vars: |
          API_KEY=${{ secrets.API_KEY }}
          PORT=8080
        flags: '--allow-unauthenticated'